version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: nest-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: nest-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mongo_data:
